# Generated by Django 3.0.7 on 2020-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200906_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapervalues',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
